/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.securekeys.views;

import br.com.securekeys.DAO.VerifyDAO;
import br.com.securekeys.views.formScreen.LowercaseDocumentFilter;

import javax.swing.text.AbstractDocument;

/**
 *
 * @author adimael
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();
        jLabelSecureKey = new javax.swing.JLabel();
        jLabelicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeliconPassword = new javax.swing.JLabel();
        placeHolderPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnEsqueceuPass = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabeliconUser = new javax.swing.JLabel();
        placeHolderUser = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabelSubTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(988, 647));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setOpaque(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSecureKey.setFont(new java.awt.Font("Inter", 1, 48)); // NOI18N
        jLabelSecureKey.setText("SecureKey");
        bg.add(jLabelSecureKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabelicon.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("br/com/securekeys/icons/image3.png"))); // NOI18N
        bg.add(jLabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeliconPassword.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("br/com/securekeys/icons/senha.png"))); // NOI18N
        jPanel2.add(jLabeliconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, -1, -1));

        placeHolderPass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderPass.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderPass.setText("Digite sua senha....");
        placeHolderPass.setEnabled(false);
        placeHolderPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                placeHolderPassKeyReleased(evt);
            }
        });
        jPanel2.add(placeHolderPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 510, 60));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPasswordField1.setMinimumSize(new java.awt.Dimension(64, 25));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 520, 60));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 164, 121));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnEsqueceuPass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEsqueceuPass.setForeground(new java.awt.Color(0, 153, 204));
        btnEsqueceuPass.setText("Esqueceu a senha? Clique aqui.");
        btnEsqueceuPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnEsqueceuPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 164, 121));
        jLabel8.setText("Username");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabeliconUser.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("br/com/securekeys/icons/user.png"))); // NOI18N
        jPanel2.add(jLabeliconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, 60, -1));

        placeHolderUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderUser.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderUser.setText("Digite seu nome de usuário....");
        placeHolderUser.setEnabled(false);
        placeHolderUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderUserKeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 510, 60));

        jUsernameField.setBackground(new java.awt.Color(204, 255, 204));
        jUsernameField.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        jUsernameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jUsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsernameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jUsernameFieldKeyTyped(evt);
            }
        });

        /**
         * Obriga que campo UserName seja preenchido apenas com letras minúsculas
         */
        AbstractDocument doc = (AbstractDocument) jUsernameField.getDocument();
        doc.setDocumentFilter(new LowercaseDocumentFilter());

        jPanel2.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 520, 60));

        btnLogin.setBackground(new java.awt.Color(0, 102, 0));
        btnLogin.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, 60));

        jLabelSubTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelSubTitle.setText("Sistema de gestão");
        jPanel2.add(jLabelSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 670, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("br/com/securekeys/img/blob-scene-haikei (1).png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("br/com/securekeys/img/blob-scene-haikei (1).png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placeHolderUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderUserKeyTyped

    private void jUsernameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameFieldKeyTyped

    private void jUsernameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameFieldKeyReleased
        // TODO add your handling code here:
        if(jUsernameField.getText().isEmpty()) {
            placeHolderUser.setVisible(true);
            placeHolderUser.setEnabled(false);
        } else {
            placeHolderUser.setVisible(false);
            placeHolderUser.setEnabled(false);
        }
    }//GEN-LAST:event_jUsernameFieldKeyReleased

    private void placeHolderPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderPassKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderPassKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        if (new String(jPasswordField1.getPassword()).isEmpty()) {
            placeHolderPass.setVisible(true);
            placeHolderPass.setEnabled(false);
        } else {
            placeHolderPass.setVisible(false);
            placeHolderPass.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        this.dispose();

        VerifyDAO verifyDAO = new VerifyDAO();

        // Se o usuário for Administrador, exibi dashboard do Admin
        // Se não for Administrador, exibi dashboard do usuário comum
        if(verifyDAO.verifySuperUser()){
            br.com.securekeys.views.DashboardScreen dashboardSuper = new br.com.securekeys.views.DashboardScreen();
            dashboardSuper.setVisible(true);
        }
        else if(!verifyDAO.verifySuperUser()){
            br.com.securekeys.views.UserComum.DashboardScreen dashboardComum = new br.com.securekeys.views.UserComum.DashboardScreen();
            dashboardComum.setVisible(true);
        }

        //Depois de sair da tela de login, retornamos o estado do resultado da verificação para falso
        resultVerify = false;
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    private javax.swing.JLabel btnEsqueceuPass;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSecureKey;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JLabel jLabeliconPassword;
    private javax.swing.JLabel jLabeliconUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel placeHolderPass;
    private javax.swing.JLabel placeHolderUser;

    private boolean resultVerify;
    // End of variables declaration//GEN-END:variables
}
